name: Deploy to FTP Server

on:
  push:
    branches:
      - main # Trigger deployment on push to the `main` branch

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Deploy files to FTP server
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.yohannes-sisay.com
          username: main@yohannes-sisay.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist
          server-dir: /personal-book
